[package]
name = "chester-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
poise = "0.6.1"
serenity = "0.12.4"
songbird = "0.5.0"
tokio = { version = "1.47.1", features = ["full", "rt-multi-thread"] }
tracing-subscriber = "0.3.20"
