[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
## [{{ version }}] — {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}
{%- endfor %}

{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
since_commit = "2a7d5851"

commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->Features" },
    { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
    { message = "^refactor", group = "<!-- 2 -->Refactor" },
    { message = "^perf", group = "<!-- 3 -->Performance" },
    { message = "^docs", group = "<!-- 4 -->Documentation" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore", skip = true },
]

tag_pattern = "v[0-9]*"
